name: Build Modules

on:
  push:
    tags:
    - '*'

env:
  NODE_VERSION: "20.x"

jobs:
  build:
    name: Build Modules
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ ubuntu-24.04, macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        if: matrix.os != 'ubuntu-24.04'
        run: npm install

      - name: Install node-tgz-downloader
        if: matrix.os == 'ubuntu-24.04'
        run: npm install -g node-tgz-downloader

      - name: Download tarball
        if: matrix.os == 'ubuntu-24.04'
        run: download-tgz package-json --directory tarballs package.json && download-tgz package-lock --directory tarballs package-lock.json

      - name: Create module zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: '7z'
          filename: "release-${{ matrix.os == 'ubuntu-24.04' && 'sources' || matrix.os }}.7z"
          custom: -t7z -m0=lzma2 -mx=9 -aoa -mfb=64 -md=32m -ms=on -d=1024m -mhe
          exclusions: '*.git*'

      - name: Upload Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release-${{ matrix.os == 'ubuntu-24.04' && 'sources' || matrix.os }}.7z"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
