name: Build Modules

on:
  push:
    tags:
    - '*'

env:
  NODE_VERSION: "20.x"

jobs:
  build:
    name: Build Modules
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-24.04, windows-latest, macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        if: matrix.os != 'ubuntu-24.04'
        run: npm install

      - name: Install node-tgz-downloader
        if: matrix.os == 'ubuntu-24.04'
        run: npm install -g node-tgz-downloader

      - name: Download tarball
        if: matrix.os == 'ubuntu-24.04'
        run: download-tgz package-json --directory tarballs package.json && download-tgz package-lock --directory tarballs package-lock.json

      - name: Create module zip
        uses: JellyBrick/zip-release-fork@0.7.7
        with:
          type: '7z'
          filename: "release-${{ matrix.os == 'ubuntu-24.04' && 'sources' || matrix.os }}.7z"
          custom: "-mx9 ${{ matrix.os == 'ubuntu-24.04' && '-md1536m -mfb273 -mmt3' || '' }}"
          exclusions: '*.git*'

      - name: Upload Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release-${{ matrix.os == 'ubuntu-24.04' && 'sources' || matrix.os }}.7z"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
